# Welcome to Jekyll!
# Site settings
title: Giordano Fausti
email: fausti.giordano@gmail.com
description: >- 
  Computational physicist with 5+ years of experience in large-scale simulations, 
  active matter systems, and High-Performance Computing. Currently pivoting 
  towards Scientific Machine Learning (SciML).
twitter_username: 
github_username: tartopinto
minimal_mistakes_skin: sunrise # Puoi provare "air", "aqua", "contrast", "dirt", "neon", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: Europe/Rome

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Settings
author:
  name    : "Giordano Fausti"
  avatar  : "/assets/images/bio-photo.jpg" # Ricorda di caricare la tua foto qui
  bio     : "Simulation Intelligence & Computational Physics Researcher. Focused on SciML, Active Matter, and HPC."
  location: "Rome, Italy"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giordanofausti/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tartopinto"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:fausti.giordano@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giordanofausti/"
    - label: "GitHub"
